lab8_p1: p1.c
	gcc -pthread -o main p1.c
	./main Hello there

lab8_p2: p2.c
	gcc -pthread -o main p2.c
	./main 10 5

lab8_p3: p3.c
	gcc -pthread -o main p3.c
	./main 10 5

.PHONY: clean

clean:
	rm -f main